### ISSUE TITLE
[BUG] Spells added to feature do not show on Spellbook.

### ISSUE THREAD

**Issue by KonteiKeisei** [PwQt/magic-items-2#101]
**Module Version:** v4.0.0

**Before open any issue**
Debugging Enabled
No Exception in Console

**Describe the bug**
Spells added to items show in spellbook tab.
Spells added to features do not.

**To Reproduce**
1. Create Item, Add Spells, Attune/Equip - Spells show up
2. Create Feature, Add Spells, Attunement/Equip is not an option for this item type - Spells do not show up

**Expected behavior**
Spells added to a feature show in spell book tab

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/49371326/832ed835-98f8-429f-b15a-318a67f549fe)

**Browser:**
FLC (Latest)

**Foundry Version:v11.315** 

**Game System:*3.0.4* 

**Additional context**
Migration was completed when 4.0 update was applied.
Using Latest 3.0.4 compatible Tidy5e Release from KGAR, fails on stock sheet as well however.

**Comment by PwQt** [comment]
Please confirm whether you have this
![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/ffc60242-99a3-4e7f-82c6-e8c42ebc1aa4)

Setting not selected.

Are there any console messages?

**Comment by KonteiKeisei** [comment]
I do have that selected.
I saw no Magic Items related console messages during any part of the workflow (Item create, add, activate, spell changes, etc)

**Comment by KonteiKeisei** [comment]
Deselecting the identify option fixes this, however, Feats do not have an identification property from what I can tell.

**Comment by PwQt** [comment]
> Deselecting the identify option fixes this, however, Feats do not have an identification property from what I can tell.

Yes, that is the bug, will try to fix that for 4.1.0

**Comment by PwQt** [comment]
This will be fixed in 4.1.0
