### ISSUE TITLE
[BUG] Casting spells with concentration does not work at all in dnd5e 4.1

### ISSUE THREAD

**Issue by nschoenwald** [PwQt/magic-items-2#104]
Casting spells with concentration does not work at all in dnd5e 4.1

<img width="439" alt="image" src="https://github.com/PwQt/magic-items-2/assets/72390280/aab2385d-6dd7-4fe1-bcaa-47df1fa5f1c3">

**Comment by nschoenwald** [comment]
This was actually appearantly caused by this issue in dfreds convenient effects: https://github.com/DFreds/dfreds-convenient-effects/issues/321

**Comment by PwQt** [comment]
I was checking that yesterday with all modules updated in prep for fixing Effects with Midi-Qol https://github.com/PwQt/magic-items-2/issues/106 and it all seemed working fine.

Closing.
