### ISSUE TITLE
Register with Foundry?

### ISSUE THREAD

**Issue by sharkbruhaha** [PwQt/magic-items-2#11]
any plans to get this registered with FoundryVTT so that it shows up in the mod list?
Could msg the admins to see about delisting the original Magic Items as abandoned, and this could go in place with same name.

**Comment by PwQt** [comment]
Unfortunately that won't happen soon, I don't own the licence, and friend who bought it, doesn't want to publish it on FVTT DB as "him". 

I'll see what I could do about it later this year.
