### ISSUE TITLE
[BUG] UI Warning on world load like: "magicitems | Your controlled Actor does not have a spell/feat named Disguise Self"

### ISSUE THREAD

**Issue by ctbritt** [PwQt/magic-items-2#111]
**Module Version:** v4.1.3
**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Getting two yellow warning banners on world load that says my controlled actor doesn't have a spell/feat named Disguise Self

**To Reproduce**
1. enable magic items
2. reload world
3. See warning

**Expected behavior**
No warning presented 

**Screenshots**
![CleanShot 2024-04-11 at 13 24 12](https://github.com/PwQt/magic-items-2/assets/4516034/ae73286c-7998-4e1d-b227-8859b32b04be)
**Browser:**
 Chrome 123.0.6312.106

**Foundry Version:** 
11.315
**Game System:** 
DnD5e 3.1.2

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by ctbritt** [comment]
I have tested this with no modules other than Magic Items, libwrapper, socketlib and module management+... I have even deleted an item with Disguise Self from the tokens on the grid. and still get the issue.

**Comment by PwQt** [comment]
Yes, it's this module's issue, I'll try and have it fixed asap.

**Comment by PwQt** [comment]
What happens if you remake the items in the compendiums?

**Comment by Janner3D** [comment]
![image](https://github.com/PwQt/magic-items-2/assets/35965176/45966620-49db-4c4c-aab6-af5be959dba4)
![image](https://github.com/PwQt/magic-items-2/assets/35965176/3e2a5662-599c-4a35-9448-241e49aeb0b5)
I'm getting the same issue

**Comment by rtschaefer** [comment]
I am getting the exact same yellow banners for a multitude of spells, and even when the implicated magic items and spells are deleted it still occurs. I hope this can get resolved soon, but if not, I will need to deactivate the module (which I really do not wish to do!).

**Comment by PwQt** [comment]
Should no longer be present in [4.1.4](https://github.com/PwQt/magic-items-2/releases/tag/4.1.4)

**Comment by AmebaPululante** [comment]
Hello there,

I'm still getting this error sometimes in 4.1.4:

![image](https://github.com/PwQt/magic-items-2/assets/55915641/4c16a6bd-aada-4d79-a220-bffb7c54886d)

Could you look into it?

Thanks in advance!

**Comment by Sinled** [comment]
> Hello there,
> 
> I'm still getting this error sometimes in 4.1.4:
> 
> ![image](https://private-user-images.githubusercontent.com/55915641/329744838-4c16a6bd-aada-4d79-a220-bffb7c54886d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODcyMjgsIm5iZiI6MTcxNjI4NjkyOCwicGF0aCI6Ii81NTkxNTY0MS8zMjk3NDQ4MzgtNGMxNmE2YmQtYWFkYS00ZDc5LWEyMjAtYmZmYjdjNTQ4ODZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMjIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZTZhMGFlZDdkY2NmM2VkYjRiNjI2YmI4MzEyZmMyYjE4YmRiOGZlYjAzMmI1MGEyOTY3NDVkZDBjNGRjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XHSv51oFTkAQR4Th7z8T6I8K_IhM3rdSCz6pbe4w9G0)
> 
> Could you look into it?
> 
> Thanks in advance!

Not sure if it helps, but for me it wasn't working when i was dropping spell from "omnisearch" popup. When i imported spell and then added it to item it started to work fine.
