### ISSUE TITLE
Write out "total" instead of abbreviating it to "tot"

### ISSUE THREAD

**Issue by nschoenwald** [PwQt/magic-items-2#122]
There is plenty of space in the character sheet there:
<img width="1011" alt="image" src="https://github.com/PwQt/magic-items-2/assets/72390280/9143b728-d4f0-46c7-a181-b5c02353e86d">

In my native language German, "tot" means "dead", which is always weird to see as the abbreviation there 😅

**Comment by PwQt** [comment]
Modified that via Weblate, will be fixed in next release
