### ISSUE TITLE
[BUG] Spells appear only on PCs sheets, but not on NPCs

### ISSUE THREAD

**Issue by TheMightyTeo** [PwQt/magic-items-2#128]
**Module Version:** v4.1.2.1

**Describe the bug**
Spells do not appear if item, scroll, wand is equipped by an NPC

**To Reproduce**
1. Create two new actors. Set their type to PC and NPC.
2. Create any of: wand, staff, scroll, go to 'Magic Item' tab and set to True: 'Is a Magic Item?', 'Activation Options - Equipped', 'Max Number of Charges - 1 On Item', 'Destroy Item At 0 Charges - True, Always, Just Destroy'. Drag and drop any spell you like.
3. Give created item to both PC and NPC.
4. Equip the item by both actors and go to 'Spells' tab
5. See the spell added by magic item on PCs sheet, but not on NPCs sheet

**Expected behavior**
Spells added via Magic Items should be added to both PCs and NPCs

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/163724679/c9959a46-73a5-4453-8096-4118f49d6bff)
![image](https://github.com/PwQt/magic-items-2/assets/163724679/365539ef-cf44-4766-b989-020834b404eb)

**Browser:**
 - Foundry Lightweight Client

**Foundry Version:** 
11.315

**Game System:** 
D&D5e 3.1.2

**Additional context**
Add any other context (like other modules installed) about the problem here.
Tidy5e Sheets 3.3.0

**Comment by PwQt** [comment]
Is this still reproduceable? I can't reproduce that on classic and in Tidy5e.

Does the spell disappear whenever you remove an item?

_Also your spell also required Attuned on the item_

**Comment by PwQt** [comment]
Cannot reproduce
