### ISSUE TITLE
Token Action HUD Compatibility and additional Tidy Sheet tab

### ISSUE THREAD

**Issue by LupusVentus** [PwQt/magic-items-2#129]
Title. Cuz right now the only option to use active stuff is through the sheet. Also, maybe, an additional sheet tab just for Magic Items thing?

**Comment by PwQt** [comment]
https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/issues/85

For adding Magic Items spells to Token Action HUD consult this post.

I won't be making another tab for Spells from items.
