### ISSUE TITLE
[BUG] "Item "[ItemID]" does not exist!" is shown when an item is exhausted.

### ISSUE THREAD

**Issue by alessiocali** [PwQt/magic-items-2#132]
**Module Version:** v4.1.4
[console-export-2024-4-28_18-24-13.txt](https://github.com/PwQt/magic-items-2/files/15142991/console-export-2024-4-28_18-24-13.txt)

**Describe the bug**
When casting an item's spell would result in the item being destroyed, an error message is shown as an overhead. The error mentions "Item [ItemID] does not exist".

**To Reproduce**
1. Create any magic item with 1 charge and 1 spell.
2. Make sure the item would be destroyed at 0 charges.
3. Give the item to any actor.
4. From the spell tab, use the item's spell.
5. Notice that an error message pops in red.

**Expected behavior**
There shouldn't be any error shown when an item is consumed.

**Browser:**
 Firefox 125.0.2

**Foundry Version:** 
11.315

**Game System:** 
DnD 5E 3.1.2

**Comment by PwQt** [comment]
This might be solved by #157 - to verify after the 4.1.7 release
