### ISSUE TITLE
[BUG] Recharge on Long rest is not working

### ISSUE THREAD

**Issue by Avitale34** [PwQt/magic-items-2#134]
**Module Version:** v0.0.0

**Before open any issue**

**Describe the bug**

**To Reproduce**
1) Create a Magic Item
2) set charges and recharge on long rest formula
3) expend spell
4) Take long rest and the spells do not recharge.

**Browser:**
Chrome

**Foundry Version:** 
11
**Game System:** 
dnd5e
**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by nivthefox** [comment]
Not working on short rest either.
