### ISSUE TITLE
[BUG] Unable to add multiple spells to a magic item

### ISSUE THREAD

**Issue by danscod** [PwQt/magic-items-2#139]
![image](https://github.com/PwQt/magic-items-2/assets/4407257/fed7077f-d1d3-4db2-8feb-6295452053e1)
![image](https://github.com/PwQt/magic-items-2/assets/4407257/b8b1f6f8-965d-4df2-b7a7-72d639373871)

I was adding spells to a magic item, and while 2 seemed to be added succesfully, adding a third didn't work and then all spells were missing from the item page and unable to return. This is running on Foundry v11.315, D&D system 3.1.2

**Comment by PwQt** [comment]
No response - I can't reproduce it on my own. I'm not locking the convo in case it pops up again.
