### ISSUE TITLE
[Feature Request] Copy instead of linking to the item

### ISSUE THREAD

**Issue by GhostwheelX** [PwQt/magic-items-2#140]
Would it be possible to create a "copy" of the spell within the magic item instead of linking it to the item in the items tab?

So currently, if you import a spell into an item from the items tab, and then the original is deleted (the one in the items tab, not the one on the magic item within the character sheet), then the item in the character sheet stops working, which is a problem.

**Comment by PwQt** [comment]
No, it'd require rewrite of the whole module
