### ISSUE TITLE
[Translation Request]Add Japanese

### ISSUE THREAD

**Issue by shiro-panda** [PwQt/magic-items-2#148]
Would you add Japanese to Hosted Weblate Component?
I can provide translated glossary.

**Comment by PwQt** [comment]
https://hosted.weblate.org/projects/magic-items/main-translation/ja/ should you want to use Weblate

**Comment by shiro-panda** [comment]
I added it to Weblate. Plz check it.
I'm not sure it went right cuz its first time I use it.

**Comment by PwQt** [comment]
Looks okay, I'll add it to the next planned release, if something looks wrong after that, please modify the weblate strings

**Comment by shiro-panda** [comment]
thanks a lot!
