### ISSUE TITLE
Enable for use with Features also

### ISSUE THREAD

**Issue by AAUCrisp** [PwQt/magic-items-2#152]
I'm just writing to suggest making it work with _Features_ also.

Until now I've been using the *Items with Spells* module which has this feature.
I did try out this module at some point and really like how everything is set up, but was missing the ability to use it for *Features* so changed back.

Now *Items with Spells* isn't being updated anymore, so I'm caught between a rock and a hard place.

I know it's not your problem, but thought I'd suggest it anyway, as I might not be the only one feeling this way.

**Comment by PwQt** [comment]
It is working for features also.

**Comment by AAUCrisp** [comment]
Holy s***!!

I'm sorry then 😅

With the readme saying:  `Once activated, a new tab named 'Magic Item' will be available for each items of type 'weapon', 'equipment' or 'consumable'.`

Specifically mentioning item types like that gives a different impression.

I'm looking super much forward to giving it another go then 🥳

Thank you

**Comment by PwQt** [comment]
Ye, the readme is long overdue for a rehaul, but i'm waiting for the NPC+Item sheets to be redone so that I finally have the motivation for it 😅 .
