### ISSUE TITLE
Compatibility with Argon Combat HUD

### ISSUE THREAD

**Issue by VirusNik21** [PwQt/magic-items-2#159]
Big request to add compatibility with Argon Combat HUD from Theripper93 - namely: at the moment the spell from the item is not recognized as an action of the type "Spell" in the above module. For example in a similar module Item with Spells it is realized, but I like your module better. Thank you very much in advance.

**Comment by PwQt** [comment]
Please consult: https://github.com/PwQt/magic-items-2/issues/19

You'd have to pester theripper93 about it, sorry.
