### ISSUE TITLE
[BUG] Unable to load valid module Manifest

### ISSUE THREAD

**Issue by Elfenduil** [PwQt/magic-items-2#17]
Hello,

When I try to install the module I get an error message, see screenshot.

I'm running Foundry 11.307

Thanks in advance

![image](https://github.com/PwQt/magic-items-2/assets/65708216/d7037d6a-f27a-499a-bcd3-be81436c3635)

**Comment by PwQt** [comment]
@Elfenduil try to download it from 
```
https://github.com/PwQt/magic-items-2/releases/download/1.3.2/module.json
```

**Comment by Elfenduil** [comment]
Perfect :)
