### ISSUE TITLE
[BUG]  Magic Items do not shows up on NPC sheet

### ISSUE THREAD

**Issue by gioppoluca** [PwQt/magic-items-2#177]
**Module Version:** v4.2.1
**Describe the bug**
Magic Items do not shows up on NPC sheet

**To Reproduce**
create a magic item with a spell, give it to the NPC; nothing gets shown

**Expected behavior**
Magic Item works also on NPC

**Browser:**
 - Foundry app

**Foundry Version:** v12.330

**Game System:** dnd5e 3.3.1

**Additional context**

**Comment by PwQt** [comment]
Cannot reproduce it :/
