### ISSUE TITLE
[BUG] It's not showing the name of the spell, neither in the item nor in the grimoire

### ISSUE THREAD

**Issue by antoniohbmonteiro** [PwQt/magic-items-2#178]
When i drag a spell to "magic item" is add, but not getting the name...
old ones(already have names) is ok.

I put a "Test" where there was no text, in all items the name of the spells does not appear.

This is only for new ones, old ones is ok.

when i add the spell, is not showing any error log.

print in the "grimoire":
![image](https://github.com/user-attachments/assets/41c9a24f-feaa-497a-a146-545cb173d9d9)

**Comment by PwQt** [comment]
Coul you please post images of how your magic item tab is looking?

**Comment by antoniohbmonteiro** [comment]
It's only with SRD spells(chris premades and custom ones is ok)... It's happening even without the translation into Portuguese

![Captura de tela 2024-09-11 212915](https://github.com/user-attachments/assets/fe9fec0b-b4e7-4d73-becc-27f9c30797ae)
![Captura de tela 2024-09-11 212804](https://github.com/user-attachments/assets/87da5590-82f0-4ec0-a932-454d7ebb18f0)

**Comment by PwQt** [comment]
Do you by any chance use Babele module or any other that would rename?

Please post the full item (first screenshot)

**Comment by antoniohbmonteiro** [comment]
sorry the late response...

yes i use babele

this print is what u want?
![Captura de tela 2024-09-23 140437](https://github.com/user-attachments/assets/30ecd805-4458-4579-9d4b-95f7dbc87025)

**Comment by PwQt** [comment]
I've tested that, it seems to be working fine for me...

Could you please post your module list?

**Comment by PwQt** [comment]
I managed to reproduce it, unfortunately I can't seem to fix the "broken" spells that are present in an item, so you'd have to readd them to the item when the next version is released.
