### ISSUE TITLE
[BUG] Compatability with Token Action HUD 5e

### ISSUE THREAD

**Issue by ChobitsCrazy** [PwQt/magic-items-2#18]
**Module Version:** v1.3.2

**Before open any issue**
Nothing showing in Console

**Describe the bug**
Unable to get Magic item spells to show up in the Action HUD for 5e

**To Reproduce**
1. Created a new item, made the item magical, added the ability to cast Cure Wounds on equip.
2. Equipped the item to a PC, the spell shows in the spell list
3. Check the spells section on Token Action HUD 5e and it is not listed

**Expected behavior**
Spell should show up to be cast.

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/21301107/7b541f9b-5a8f-4bfb-869e-0885e0ca5259)
![image](https://github.com/PwQt/magic-items-2/assets/21301107/961ff413-0829-4170-9678-912cf7a85d5b)
![image](https://github.com/PwQt/magic-items-2/assets/21301107/d3e03e44-a56a-42ff-b701-4caf3c3e96ef)

**Browser:**
Using App

**Foundry Version:** 
v11.308
DnD5e - v2.3.1

**Comment by PwQt** [comment]
Should be [working](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/issues/59). 

I'll return to you in couple of days to see if that's this module's issue, or did something break with Token Action HUD.

**Comment by PwQt** [comment]
https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/issues/73
