### ISSUE TITLE
[BUG] Certain spells fail to trigger, such as reaction spells like Shield

### ISSUE THREAD

**Issue by Bryn1701** [PwQt/magic-items-2#182]
**Module Version:** 4.2.2.1

**Describe the bug**
When ever there is a reaction spell put into the item via Magic Items such as shield, it will not trigger when the target gets hit. Also I have noticed that when a Fireball is placed inside the item via Magic items it throws a level 3 fireball correctly, but any upcasting will cause it to produce the level 3 version regardless of level upcast selected. This does not produce any error in the console. 

**Foundry Version:** 
v12 331

**Game System:** 
D&D 5e 3.3.1

**Comment by PwQt** [comment]
About first bug:

Do you use Midi-Qol?

2nd: https://github.com/PwQt/magic-items-2/issues/169

**Comment by Bryn1701** [comment]
Indeed I do use Midi-Qol. As for the up cast bug, I did indeed see the other post, but I thought it was from awhile ago and didn't want to skip the issue if it had been fixed and broken again in a recent update. My apologies for the double post.

**Comment by PwQt** [comment]
![obraz](https://github.com/user-attachments/assets/2a2962e0-1c94-48e5-a112-072db3ae40d5)

Do you use those settings in Reaction tab in MidiQol settings? That should make the "reaction" spells work.

**Comment by Bryn1701** [comment]
Indeed I have those settings. 
<img width="597" alt="04753854cd5940a0ad9c9cdc526a1899" src="https://github.com/user-attachments/assets/29eaf718-8671-45d5-8f5c-50b6c68747e9">

**Comment by Bryn1701** [comment]
Ok this is very odd. Upon further testing. Reaction spells such as shield on the magic item does work as intended. The testing token is borked for some reason and wont activate ANY reactions. I will have to look into it further, but it is working as intended for reaction spells baked into magic items. My apology for the report.
