### ISSUE TITLE
Compatibility with Argon

### ISSUE THREAD

**Issue by noncasus** [PwQt/magic-items-2#19]
Any chance to get this module to work with Argon Combat HUD? No features or spells show up in the HUD menus.

**Comment by PwQt** [comment]
It's up to the Argon Combat HUD owner to do that, and he seems adamant to do it.

There have been 4 issues made there about it: https://github.com/theripper93/enhancedcombathud/issues/86 https://github.com/theripper93/enhancedcombathud/issues/76 https://github.com/theripper93/enhancedcombathud/issues/30 https://github.com/theripper93/enhancedcombathud/issues/62
