### ISSUE TITLE
[ Cant open the spell in the spellbook]

### ISSUE THREAD

**Issue by Asiermd** [PwQt/magic-items-2#194]
**Module Version:** v4.2.4

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
When i try to open a spell in a magic item in the spellbook tab the spell doesnt open.

**To Reproduce**
1. Create a magic item with a spell
2. click on the spell in the spellbook tab
3. the error appears
**Expected behavior**
The spell to open like normal

**screenshot**
![image](https://github.com/user-attachments/assets/57135e12-5552-481d-a78c-e31cded48ab8)

**Browser:**
Versión 129.0.6668.103 (Build oficial) (64 bits)

**Foundry Version:** 
version 12 stable build 331
**Game System:** 
dnd 3.3.1
**Additional context**
I have tidy 5e sheet installed, but tried on the normal sheet with and without tidy installed and even used "find the culprit", the bug was always there

**Comment by PwQt** [comment]
Are you opening the sheet as a player or as a GM?
