### ISSUE TITLE
Deprecation of Item5e.roll

### ISSUE THREAD

**Issue by PwQt** [PwQt/magic-items-2#2]
**Describe the bug**
Item5e#roll will be deprecated, a quick fix to Item5e#use is required.

**To Reproduce**
1. Use a spell that requires targeting an enemy

**Screenshots**
![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/c734c629-19c0-4f88-9a67-e9098f7ee7bc)

**Foundry Versions:**
 - DND5e version: 2.2.1
 - Foundry: 11.301

**Comment by YakFromStateFarm** [comment]
Hey, So I ran into this bug when trying to get another module to work with magic-items-2. I found the solution, and can make a fork and PR if youd like me to just do that for you. No problem at all :)

**Comment by PwQt** [comment]
I'll try to find time this week to update it, already found the part where to update it, just couldn't find the time to do it, should be done before next week.

**Comment by PwQt** [comment]
Fixed in [1.2.0](https://github.com/PwQt/magic-items-2/releases/tag/1.2.0)
