### ISSUE TITLE
[BUG] With Ready Set Roll it duplicates the chat message for feature/spell on item

### ISSUE THREAD

**Issue by Dalton1310** [PwQt/magic-items-2#22]
**Module Version:** v1.3.2

**Describe the bug**
This bug creates 2 chat logs for every time you use a feature or spell and makes nulls one of the chat logs ability to make targets roll save, take damage, heal, or apply effect.

**To Reproduce**
1. Create an item
2. Give the item a spell or feature
3. Give the item to a character
4. Have the character use the spell or feature
5. 2 chat logs of that spell or feature shows up and only one can be used, the other is an error

**Expected behavior**
The item feature/spell should only give one chat prompt that allows targets to click on to roll for a save, as well as to click on if there is an effect to give if they fail. This bug also removes the most current chat of the two saying that it isn't attached to an item anymore

**Screenshots**
![1](https://github.com/PwQt/magic-items-2/assets/64174287/64127f8b-84aa-4321-90a4-a706483de853)
![2](https://github.com/PwQt/magic-items-2/assets/64174287/c129fefe-c8ce-4a25-ae91-178970cbca65)
![image](https://github.com/PwQt/magic-items-2/assets/64174287/4c87636c-7fa9-428c-a389-4e6dcbee8089)
![image](https://github.com/PwQt/magic-items-2/assets/64174287/6756a850-3aea-4c7b-93ec-973c1810d9ae)
That one is if you click the lower chat log save.
![image](https://github.com/PwQt/magic-items-2/assets/64174287/b9e1af95-1866-422c-bca6-19ea559534c5)

**Foundry Version:** Version 11, latest Module update

**Additional context**
Ready Set Roll 2.1.2 is the only module that does anything with chat logs for features and spells.

**Comment by Dalton1310** [comment]
This was left in magic items 1 as a comment that may possibly solve the issue? 
"Hey I just stumbled into this issue not being solved after 2 months. As a fellow developer I know it is easy to throw "compatibility issue" onto other software, but I think the solution here is fairly simple.
I glanced through the code for the module and found code that seem to cause the issue. In OwnedMagicItemSpell.roll().proceed() it calls ChatMessage.create(_) directly, so adding simple condition check here to not post your own message when RSR is enabled would probably solve all issues with doubled chat card."

**Comment by david-simoes-93** [comment]
https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/91

**Comment by PwQt** [comment]
Should be fixed in https://github.com/PwQt/magic-items-2/releases/tag/1.4.0

**Comment by Dalton1310** [comment]
This did not seem to work for me, updating to 1.4.0 but thank you for the effort!

**Comment by david-simoes-93** [comment]
Issue still exists in 1.4.4
