### ISSUE TITLE
NPC - Don't see spells on coming from item[BUG]

### ISSUE THREAD

**Issue by thomasjeffreyandersontwin** [PwQt/magic-items-2#23]
**Module Version:** 1.3.2
foundry 11.313
dnd  5e 2.3.1
![screen1](https://github.com/PwQt/magic-items-2/assets/788604/8d31872e-2fdf-48e1-ae4e-231a5742bad7)
![screen1](https://github.com/PwQt/magic-items-2/assets/788604/26cf3f9a-50d2-4aaf-95e2-6bb596804068)

didnt see any errors or warning on the console

1) Click F12 go to the _console_ tab 
2) make the test you want and replicate the error
3) Go to the tab console open in point 1) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
4) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**

**To Reproduce**
1. Opened up an NPC Actor with a Magic Item
2. Added spells to magic item
3. equipped item
4. spells do not appear in character sheet
5. Note: Yhis worked on a PC actor

**Comment by PwQt** [comment]
You should probably check the checkbox of having the item equipped for NPCs, it seems to be working on the newest 5e/FoundryVTT version for me.

I'll see though if it's not a bug.

![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/91d293e0-e3df-4572-9dfc-accb58ca4de3)
![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/dad271ba-e555-4143-98a6-fa38694e6ba1)
