### ISSUE TITLE
[BUG] Players cannot drag/drop spells into items

### ISSUE THREAD

**Issue by DracLore1** [PwQt/magic-items-2#24]
**Module Version:** v1.3.2

**Describe the bug**
Players are unable to attach spells to items from the Compendiums or the Items section

**To Reproduce**
1. Log in as player
2. select/create an item and go to the Magic Item tab
3. Click is magiv item
4. Drag a spell into the "Drag spells/feats here' box
5. Nothing happens

**Expected behavior**
The above should add the spell to the item

**Screenshots**

**Browser:**
Tested in both - Firefox, Chrome

**Foundry Version:** 
11 Stable 315

**Additional context**
Was working in Magic Items in v10, since updating to v11 and changing to magic items 2 it no longer works, I have checked all permissions for players and still nothing aside from being the GM works

**Comment by PwQt** [comment]
Reproducable - i'll fix it during this week.
