### ISSUE TITLE
[BUG] Odd permission request

### ISSUE THREAD

**Issue by stgreenb** [PwQt/magic-items-2#29]
**Module Version:** Magic Items 2 v1.3.3 & Tidy5e Sheet v0.10.0

**Describe the bug**
When a user clicks on the name of a spell that's on a magic item at the bottom of their spell list (not the icon), the user is prompted that they don't have the permission to view the sheet. 
![image](https://github.com/PwQt/magic-items-2/assets/18483964/19ebd7e9-7c75-423f-a22b-cf8125749514)

In this case the user is a "trusted player" but its not obvious what permission they are lacking to not get the above error. 
![image](https://github.com/PwQt/magic-items-2/assets/18483964/852b1263-1166-4fed-8bf6-5813cb11d298)

**Browser:**
Firefox and Chrome

**Foundry Version:** 
![image](https://github.com/PwQt/magic-items-2/assets/18483964/b2557744-098a-4134-a983-aa061eea6191)

**Comment by SirGarhi** [comment]
they need ownership of the item document being referenced if you want them to be able to open and/or edit its sheet

**Comment by PwQt** [comment]
That I think is an issue with spells/system permissions than anything this module could handle.
