### ISSUE TITLE
Issues with Token Action HUD 5e

### ISSUE THREAD

**Issue by YakFromStateFarm** [PwQt/magic-items-2#3]
Having an issue with the Token Action HUD where is seems like the spells from Magic Items are not showing properly. Was wondering if anyone else had encountered this error, as it is kind of a major one and I havent worked with the code in this module much yet so dont even know where to begin haha.

**Comment by PwQt** [comment]
Original author has not supported that module, I'll try to look into it.

Was it [this](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e) module ?

**Comment by YakFromStateFarm** [comment]
So it used to work on V10, but seems not to on V11. And is Token Action HUD also not worked on? I was going to ask if you wanted a second set of eyes on this code as it seems like youre taking over the module, but I can also take a look at the HUD. I was looking to add Magic Items to theRipper's Argon HUD so this wouldnt be much different (famous last words amiright haha)

**Comment by PwQt** [comment]
I think I know the culprit why it's not working anymore (probably the issue is Action-Hud Side in [line 27](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/blob/main/scripts/magic-items-extender.js)) - this module's ID is no longer `magic-items` but `magic-items-2`. 

I'll check it out and come back to this topic when I have time.

**Comment by YakFromStateFarm** [comment]
I think I solved the issue after you pointed me in the right direction. It seems to be working now. Ill see if I cant get a PR in on the Token Action HUD repo and fix this. One thing off your plate :)

**Comment by PwQt** [comment]
Related PR: https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/pull/60
