### ISSUE TITLE
[BUG] No reaction pop up when item has a shield type spell.

### ISSUE THREAD

**Issue by Dyrnwyrm** [PwQt/magic-items-2#32]
**Module Version:** v1.3.3

No Console errors but when i added a reaction type spell (like shield) the reaction doesnt pop up on Midi, nothing, it just happen when using a spell thats part of the item, my players can react normally when using their own reactions or spells that are part of them

**To Reproduce**
Create a magic item
Add a spell that uses a reaction (shield for example)
When player gets attacked the spell doesnt pop the window for reaction on Midi but the reaction works if using feature or spells that are part of the player

**Expected behavior**
Let the player use their reactions
**Screenshots**

**Foundry Version:** 
11.315

Midi: 11.3.12.1

**Comment by MotoMoto1234** [comment]
This is actually very likely on midiqol to remedy, its on his radar but no eta.  Original MIM had a special check to account for this, Tposney just needs to take a look at how much has changed in MIM 2 first, but he's smack dab in the middle of some hefty item sheet overhauls.

**Comment by PwQt** [comment]
> Tposney just needs to take a look at how much has changed in MIM 2

the only thing that's changed from MI 1 is the module-id so it should be an easy fix, if it's really on the midi-qol side

**Comment by MotoMoto1234** [comment]
> > Tposney just needs to take a look at how much has changed in MIM 2
> 
> @MotoMoto1234 the only thing that's changed from MI 1 is the module-id so it should be an easy fix, if it's really on the midi-qol side

Tposney has added MIM 2 to the check for the old mim's reactions and fixed a few other issues but the fix is in a test release that we're still working out the kinks on.  Expect the fix in Midiqol 11.3.13, which won't be publicly available for a bit, so soon:tm:

**Comment by PwQt** [comment]
Will check with 11.3.13 Midi-Qol release

**Comment by PwQt** [comment]
Still doesn't work - will have to investigate further later.

**Comment by MotoMoto1234** [comment]
> Still doesn't work - will have to investigate further later.

It was fixed briefly and then there was a bad version where items with spells AND magic items 2 fails.  He's got an internal fix for it pending.  Also theres a typo in midi where if you have more than one type of reaction available, no reactions prompt.  All to be fixedin a release this week.

**Comment by PwQt** [comment]
Issue still persists according to #58

**Comment by PwQt** [comment]
It should be solved with [1.6.1.1](https://github.com/PwQt/magic-items-2/releases/tag/1.6.1.1)
