### ISSUE TITLE
[BUG] Unable to change any numbers. 

### ISSUE THREAD

**Issue by norraist** [PwQt/magic-items-2#33]
**Module Version:** v1.4.1

**Describe the bug**
Unable to change number of charges on item, or charges consumed by spell, or cost/lvl

**To Reproduce**
attempt to enter a whole number into any of those fields. Field reverts back to default/already existing value.

**Expected behavior**
Number to change to input

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/37781748/ea660f2e-b04f-4656-9c20-3d171f7dc4bc)

**Browser:**
multiple

**Foundry Version:** 
v11.315
**Game System:** 
DnD5e - Fifth Edition System v2.4.1

**Comment by p4535992** [comment]
Should be fixed on 1.4.2
