### ISSUE TITLE
[BUG] Deletion of Settings on Edit

### ISSUE THREAD

**Issue by RawrKrake** [PwQt/magic-items-2#37]
**Module Version:** v0.0.0

**Describe the bug**
When you click the edit button in the Description tab of an item, it will delete all the settings from the magic item tab. Sometimes reset it to a previous setting.

**Comment by p4535992** [comment]
You mean the "standard" edit button right ?

 ![](https://i.imgur.com/IdIZd0b.png)

**Comment by p4535992** [comment]
Also please a favor.. click F12 and check (or do a screenshoot) of the web console logs tab and check for any red messages.

**Comment by PwQt** [comment]
No console logs - can reproduce it.

1. Create a new blank item.
2. Add Magic Item properties
3. Go and edit "Main" description.
4. Goes into Magic Item tab with it being "blanked"

**Comment by kgar** [comment]
This may become fixed by #46

**Comment by PwQt** [comment]
Should be fixed in 1.5.0
