### ISSUE TITLE
[BUG] With Ready Set Roll it duplicates the chat message for feature/spell on item

### ISSUE THREAD

**Issue by david-simoes-93** [PwQt/magic-items-2#38]
**Module Version:** v1.4.4

Re-opening https://github.com/PwQt/magic-items-2/issues/22

Same exact issue. Solution is as simple as replacing L1143 to LL1148 by

		if (!game.modules.get("ready-set-roll-5e")?.active) {
			ChatMessage.create(
			  mergeObject(chatData, {
				"flags.dnd5e.itemData": this.ownedItem.toJSON()
			  })
			);
		}

This maintains ALL the behavior of the module, just fixes the bug when RSR is enabled by preventing the duplicate chat entry

**Comment by orpheussnacks152** [comment]
where do you apply this fix for the module?

**Comment by PwQt** [comment]
@orpheussnacks152 1.6.2 should fix this
