### ISSUE TITLE
Tidy 5e Sheet issue - item changes cause scroll reset on Details Tab

### ISSUE THREAD

**Issue by kgar** [PwQt/magic-items-2#40]
**Module Version:** v1.4.5

**Describe the bug**
When making changes to an item with the "Tidy 5e Item Sheet" option selected, if the sheet is scrolled down when the change occurs, the scroll resets to the top.

![image](https://github.com/PwQt/magic-items-2/assets/4632129/628d12f1-828f-4efb-93ad-8cf2222c7415)

![image](https://github.com/PwQt/magic-items-2/assets/4632129/dbdc8e52-5cb4-4494-9018-eef32365f51e)

**To Reproduce**
1. Open an item with "Tidy 5e Item Sheet" selected
2. Go to the "Details" tab
3. Make enough changes so that the tab has a scrollbar
4. Scroll down and make another change
5. Note that the scrollbar resets to the top

**Expected behavior**
The scroll should remain where it was before making a change to the sheet data. This would make it behave like the default sheets.

**Foundry Version:** 
11.315

**Game System:** 
dnd5e

**Additional context**
I have a PR for this, to save you some time, if you are interested in a fix.
I am the author of the Tidy 5e Sheet rewrite, but I am reporting this for the original Tidy 5e Sheet module.

**Comment by PwQt** [comment]
Merged, released in 1.4.6
