### ISSUE TITLE
[Feature] Independent Uses for each Spell

### ISSUE THREAD

**Issue by david-simoes-93** [PwQt/magic-items-2#43]
Some items, like the Staff of Thunder and Lightning, give you spells/abilities that can each be cast once per day.

![image](https://github.com/PwQt/magic-items-2/assets/9117323/d0b456ec-35eb-4928-a9d5-e7ae0b672dcb)

Would be great if the module would support this, instead of only supporting charge consumption.

**Comment by PwQt** [comment]
![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/46216362-c187-4838-b3b9-178771e78614)

Isn't that solved with those properties on the Magic Item tab, you just have to create your own spells for that?

**Comment by Girafz** [comment]
This setting does exactly what I think he was asking. As it was my question too but I did not realize it was a dropdown option.
![image](https://github.com/PwQt/magic-items-2/assets/83099397/7feed796-8d8a-4f4c-ad64-66e99c27dd57)

**Comment by PwQt** [comment]
Yes, it's that, don't know why i posted the wrong charge option. Anyways.
