### ISSUE TITLE
[BUG] New Spell with None User Permissions Dragged onto Magic Item, Permissions Issue for Player

### ISSUE THREAD

**Issue by kgar** [PwQt/magic-items-2#48]
**Module Version:** v1.5.0

**Describe the bug**
A user who owns an actor has a magic item. 
The DM drags a spell onto the magic item. Note: The user cannot normally see the spell in the items collection.
The user tries to click the new spell on the magic item.
The user sees a permissions warning, and the spell description does not show.
Also, the spell does not appear in the character sheet spellbook.

**To Reproduce**
These steps leads to a permission warning:
- A spell whose permission is set to None for a player
- An actor which the players owns
- The actor has a magic item
- Drag the spell from the items collection onto the owned magic item
- The user tries to click the spell to view it
- A permissions warning appears and the spell does not show
- Also, the spell does not show up on the character sheet

**Expected behavior**
When dragging a spell onto a magic item, it should have the same permissions as the owned item.
So, when the user clicks the spell, it should show the spell successfully.

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/4632129/ca0a3b2c-3504-4426-b2dd-d34c2fdb0166)

**Browser:**
 - Chrome, Latest

**Foundry Version:** 
11.315

**Game System:** 
dnd5e

**Additional context**
Discord discussion: https://discord.com/channels/1167985253072257115/1200922444098191551/1201723786852835338

**Comment by p4535992** [comment]
Maybe something like this can be the solution:

```javascript
let itemCloneToRender = new Item(item?.toObject());
itemCloneToRender.ownership.default = CONST.DOCUMENT_PERMISSION_LEVELS.LIMITED; // The player can't modify this anyway just read the details
const sheetCloneToRender = itemCloneToRender .sheet;
sheetCloneToRender.render(true);
```

**Comment by PwQt** [comment]
Pull request should fix it, please verify if it does and doesn't break anything more - If it does, i'll create a release tomorrow morning!
