### ISSUE TITLE
[BUG] Chat Cards for the spells not showing when the spell is cast

### ISSUE THREAD

**Issue by Ackerfe** [PwQt/magic-items-2#55]
**Module Version:** v1.5.2

**Describe the bug**
Spells added to an item don't show any chat card when cast.

**To Reproduce**
Add a spell to an item.
Click on the spell from the spellbook.
Chat card doesn't show

**Expected behavior**
Chat card should show

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/509528/9c9bb837-d405-4411-83c5-0448490d1668)
The automated animations works correctly as seen in this picture, as do the templates and everything else, but for some reason no chat card is produced.

**Browser:**
Chrome

**Foundry Version:** 
V 11.315
**Game System:** 
DND 5e 2.4.1
**Additional context**
The only thing that makes me think might be a problem is ready set rolls, but the spells are set up so that they properly show everything in chat when used, if I try to cast those spells without puttin them on an item first they work correctly.

Here's a list of modules that are active:
![image](https://github.com/PwQt/magic-items-2/assets/509528/52077789-4d3e-4a7e-bb2f-66dee2eef4fc)

![image](https://github.com/PwQt/magic-items-2/assets/509528/fbbdc5fc-785e-4668-88a7-0a084ad3f008)

![image](https://github.com/PwQt/magic-items-2/assets/509528/b0016f73-828f-4cf5-ab78-cf33eeabfa3f)

**Comment by Ackerfe** [comment]
tried deactivating ready set rolls and now it seems to work properly, so it's definitely a compatibility issue with that module

**Comment by Ackerfe** [comment]
also, tried to find the setting to enable debugging but couldn't find it in the module settings for magic items 2

**Comment by PwQt** [comment]
> also, tried to find the setting to enable debugging but couldn't find it in the module settings for magic items 2

there is none 😅 

I'll try to fix that this weekend, but it's always an issue with RSR.
https://github.com/PwQt/magic-items-2/issues/22

**Comment by Ackerfe** [comment]
The issue is different in this case though, I'm not getting any chat card at all rather than getting 2 of them, I have no idea though what could be the cause in the code as I'm not getting any error in the console so I can't hunt the bug

**Comment by PwQt** [comment]
Cause has been found, it'll be fixed this week

**Comment by crcroberts** [comment]
lol, i was hesitant to do any looking myself because you said there was no debugging, but i just cracked open the console and theres this:
![image](https://github.com/PwQt/magic-items-2/assets/11938158/0ddcc3ac-8ac8-4677-bffa-0de67820ea17)
Does that match your cause, or could that be another thing - not sure whether you are on same version

**Comment by PwQt** [comment]
Yes, I've gotten this error, I'm currently figuring out what my items are not giving into the proper field, but I've managed to make the card show at least 😅 .
