### ISSUE TITLE
[FEATURE] Automated Animations Integration

### ISSUE THREAD

**Issue by Kharmans** [PwQt/magic-items-2#57]
Animations configured with Automated Animations don't work when use a Feature from a item equipped.
There's no error on console.

**Comment by PwQt** [comment]
That's an AA module compatiblity issue - will try to do an integration for it, but it might be merged later looking at the module state

**Comment by PwQt** [comment]
@Kharmans do you have an example of a feature having an animation?

**Comment by Kharmans** [comment]
Yeah. I did various but I will paste one of then.

The first one, **Zapper**, is the item. The second, **Feixe de Energia**, is the feature.
The animation are configure on **Feixe de Energia** with _Template_, _Ray_ and the animation _jb2a.lightning_bolt.wide.blue_.

I don't know if this is relevant, but **Feixe de Energia** is on a compendium.

[fvtt-Item-zapper-YlK3f6GjYN5oJ7FX.json](https://github.com/PwQt/magic-items-2/files/14238779/fvtt-Item-zapper-YlK3f6GjYN5oJ7FX.json)

[fvtt-Item-feixe-de-energia-k8M32ApAmZM37OSz.json](https://github.com/PwQt/magic-items-2/files/14238790/fvtt-Item-feixe-de-energia-k8M32ApAmZM37OSz.json)

**Comment by Kharmans** [comment]
Okay, looks like some animations are working. I just configure a animation **On Token** and it play. The other item that I use has a **Template** animation. Maybe it's broken only on that or other animations, but **On Token** is working!

**Comment by nschoenwald** [comment]
I also ran into this issue and can confirm that Template animations do not work with spells cast from magic items.

**Comment by PwQt** [comment]
I've checked the code and it is on the Automated Animations side to be "fixed" and by that someone would have to make a PR to it.

Since MI doesn't create a real item, it has to be delivered in some other way.

**Comment by PwQt** [comment]
I've tested this today, and it should be working

**Comment by nschoenwald** [comment]
I can confirm, it does work now with current versions of both modules!

**Comment by PwQt** [comment]
It's probably fixed when I migrated back to `magicitems`, I've debugged the animation code, and it was broken for Magic Items 2.

**Comment by Kharmans** [comment]
It's still not working with animations on templates.
