### ISSUE TITLE
[BUG] MidiQOL Reactions

### ISSUE THREAD

**Issue by Kharmans** [PwQt/magic-items-2#58]
When using a item with Magic Item 2 active on it and that item give a feature tha use a reaction, the prompt if that reaction don't show.
I test it with the feature directly on the sheet, without the Magic Item 2, and it works.

**Comment by PwQt** [comment]
From what I could gather - the automatisation for Reactions is handled on midi-qol side. I'll try to verify it with the dev later during the day.

**Comment by PwQt** [comment]
Also duplicate #32
