### ISSUE TITLE
Magic spells assigned to an item disappear from user spell list.

### ISSUE THREAD

**Issue by TheMorningStarLucifer** [PwQt/magic-items-2#6]
I have an item with magic spells attached to it. Initially they will appear in the users spell list. However, after casting a spell from that item all of the spells from that item that are on the users spell list will vanish and I get an error.

<img width="336" alt="image" src="https://github.com/PwQt/magic-items-2/assets/137843163/ddb29f66-0f4d-4afe-8de2-3bf551272f4c">

<img width="423" alt="image" src="https://github.com/PwQt/magic-items-2/assets/137843163/4f6262e8-a19b-42a0-8778-75aaf0977343">

<img width="419" alt="image" src="https://github.com/PwQt/magic-items-2/assets/137843163/6cf927f2-2201-4a9d-8545-d9d8b6264221">

**Comment by PwQt** [comment]
Could you please verify if the same stuff occurs on basic sheet?

Which spell are you using? 
Which tidy5e sheet version are you using on which foundry version?
Dnd5e 2.2?

**Comment by TheMorningStarLucifer** [comment]
<img width="153" alt="image" src="https://github.com/PwQt/magic-items-2/assets/137843163/faa0c744-2c0f-4181-94e5-e4b7536ae103">

TidySheet 0.9.13

**Comment by TheMorningStarLucifer** [comment]
I tried with the basic sheet and it does the same thing.

**Comment by PwQt** [comment]
What about the rest?

**Comment by dallasrt** [comment]
When I lower the charges and cast a spell it deducts the correct amount, but all the spells disappear.

**Comment by dallasrt** [comment]
If you would like to be able to view real time I can share my screen in discord if it would help.

**Comment by PwQt** [comment]
Should be fixed in [1.2.2](https://github.com/PwQt/magic-items-2/releases/tag/1.2.2), not closing it yet, could anyone please confirm if that works correctly now?

**Comment by PwQt** [comment]
If it's still broken please open a new issue. Closing for now.
