### ISSUE TITLE
[Feature] Item charges do not reset after Long Rest

### ISSUE THREAD

**Issue by SomeFrenchGuy** [PwQt/magic-items-2#61]
**Module Version:** v1.6.0

**Describe the bug**
When I click on 'Long rest' on my character sheet, charges for my items with Long Rest recharge do not recharge and I have to recharge manually. (Might be the same for other type of recharge, I did not test it)

**Expected behavior**
Item should follow recharge rule on Long Rest

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/105923964/720671f1-162c-42c4-bace-92d8748dbf56)

**Browser:**
 - Firefox 122.0

**Foundry Version: 11 ** 

**Game System:**  DnD 3.0.1

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by PwQt** [comment]
It seems to be related to https://github.com/fantasycalendar/FoundryVTT-RestRecovery/ module, since on "clean" 3.0.1 it works perfectly ok
