### ISSUE TITLE
Spell description/rolling showing twice in chat

### ISSUE THREAD

**Issue by PwQt** [PwQt/magic-items-2#7]
**Describe the bug**
After using a spell from magic item it shows up twice in chat.

**To Reproduce**
1. Use a spell, a double message shows

**Screenshots**
![obraz](https://github.com/PwQt/magic-items-2/assets/12457218/56514139-2869-40f8-96a6-c36498918363)

**Foundry Versions:**
 - DND5e version: 2.2.2
 - Foundry versions: 10 and 11

**Additional context**
[To check solution from original repo](https://gitlab.com/riccisi/foundryvtt-magic-items/-/issues/122)

**Comment by YakFromStateFarm** [comment]
Ive been looking at this on my local devbox and I think I have the solution. If you look at magicitem.js, line 945, they way it sets up chatData by calling spell.use() is slightly off. It seems like the new use function should take in two params, both dicts, named configs and options(might be singular). Options is what sets up how the chat messages are sent, but currently the call is passing 
`{
 "configureDialog": false,
"createMessage": false
}` to the configs param. Basically the whole line should look something like this `
let chatData = await spell.use({},{
"configureDialog": false,
"createMessage": false
});
` The first {} is set to configs and then the rest is set to options.

The actual function is documented here https://github.com/foundryvtt/dnd5e/blob/master/module/documents/item.mjs. Its a fairly easy fix so I didnt fork or anything, but I can do that and make a PR if you are busy and just want the code updated.

**Comment by PwQt** [comment]
Should be fixed in [1.2.2](https://github.com/PwQt/magic-items-2/releases/tag/1.2.2)
