### ISSUE TITLE
[BUG] Spell doesn't work from magic item: "itemName is not defined"!

### ISSUE THREAD

**Issue by Janner3D** [PwQt/magic-items-2#79]
**Module Version:** v1.6.3.1

![image](https://github.com/PwQt/magic-items-2/assets/35965176/04ea4f78-f504-4aa5-8a4e-0b5b77b4aefc)
![image](https://github.com/PwQt/magic-items-2/assets/35965176/5c27be96-b4e9-4421-8ea2-22879992260f)

**Describe the bug**
Using a spell from a magic item does not work, and instead gives the above error.

**To Reproduce**
1. Create a magic item with a spell in it
2. Attempt to use the spell from the Spells tab

**Expected behavior**
The spell should be used as normal.

**Browser:** Chrome

**Foundry Version:** v11

**Game System:** 5e 2.4.1

**Comment by AmebaPululante** [comment]
I got the same one.
![image](https://github.com/PwQt/magic-items-2/assets/55915641/6a7cd9bb-7eb1-4bde-8606-6e4e12e1096f)
Foundry v11.315
DND 3.0.3
