### ISSUE TITLE
[BUG] AE not Applying

### ISSUE THREAD

**Issue by Kharmans** [PwQt/magic-items-2#84]
**Module Version:** v1.7.0

**Describe the bug**
When using a Magic Item with a feature that apply AE, the AE are not applied. I already use the macro and redo the item.

**To Reproduce**
Just configure a Magic Item with a Feature that apply an AE, use the Feature and see the AE not applying.

**Expected behavior**
The effect being applied.

**Browser:**
OperaGX LVL5 (core: 107.0.5045.60)

**Foundry Version:** 
v11.315

**Game System:** 
D&D5e v3.0.4

**Other Relevant Modules:**
MidiQOL v11.4.11.1
DAE v11.3.14

The itens that I an using: **Gancho de Escalada** with the feature **Escalada Segura**. I don't know if this is relevant, but the feature are on a compendium.

[fvtt-Item-gancho-de-escalada-Z5fKSVzf4GhRpqQw.json](https://github.com/PwQt/magic-items-2/files/14611712/fvtt-Item-gancho-de-escalada-Z5fKSVzf4GhRpqQw.json)
[fvtt-Item-escalada-segura-mc91VECtMTaSvjRS.json](https://github.com/PwQt/magic-items-2/files/14611711/fvtt-Item-escalada-segura-mc91VECtMTaSvjRS.json)

**Comment by p4535992** [comment]
Maybe this was the reason for this piece of code https://github.com/PwQt/magic-items-2/commit/4163d8fd837f2d6c8998b143ff527149675067e0 ? (didn't test it yet)

**Comment by PwQt** [comment]
I disabled it because it seemed like it was applying that automatically, but it might've been a plugin doing that for me - will check that later today and reenable it for when the plugin is not present.

**Comment by PwQt** [comment]
@Kharmans

I've managed to locate what module doubles effect - DFreds convenient effect + MIDI Qol "Apply Convenient Effect" setting is doubling the active effect window, I am currently investigating further

**Comment by PwQt** [comment]
This should be solved in 1.7.1

**Comment by Kharmans** [comment]
I update and it still doesn't works.

**Comment by Kharmans** [comment]
When I have Midi and CE activated, I roll the save of the target and if it fails, the effect are not apllied.
When I have only Midi activated, the target save are not rolling and this errors are showing on console:

![image](https://github.com/PwQt/magic-items-2/assets/112586547/45eeeec5-786b-4bb3-95b7-80d1c02439e1)
![image](https://github.com/PwQt/magic-items-2/assets/112586547/1c0cf101-716c-4a0f-af71-85dd048a389f)

**Comment by Kharmans** [comment]
Okay... I am very confusing right now. One Magic Item that I just configure applied the effect (and play the animation of Automated Animations). But I just test (again) the other Magic Item that I use and it not applied the effect.

Item that applied the effect: **Alfange de Águas de Sentina** with **Furto Vital** feature.
[fvtt-Item-alfange-de-aguas-de-sentina-7rtsbJDRUxnAf55S.json](https://github.com/PwQt/magic-items-2/files/14625841/fvtt-Item-alfange-de-aguas-de-sentina-7rtsbJDRUxnAf55S.json)
[fvtt-Item-furto-vital-zvCfVncrvZLEJ6mR.json](https://github.com/PwQt/magic-items-2/files/14625842/fvtt-Item-furto-vital-zvCfVncrvZLEJ6mR.json)

Item that doesn't applied the effect: **Abraço Demoníaco** with **Olhar do Azakana** feature.
[fvtt-Item-abraco-demoniaco-zYnLwzA4NJq6HazM.json](https://github.com/PwQt/magic-items-2/files/14625843/fvtt-Item-abraco-demoniaco-zYnLwzA4NJq6HazM.json)
[fvtt-Item-olhar-do-azakana-u5jwZQd8R8v16uKA.json](https://github.com/PwQt/magic-items-2/files/14625844/fvtt-Item-olhar-do-azakana-u5jwZQd8R8v16uKA.json)

**Comment by Kharmans** [comment]
Another update: the effect are applied when you roll a damage with the save. If you just roll the save, the effect are not applied.
