### ISSUE TITLE
An error appears in console when I create an item/feature/passive item in a NPC

### ISSUE THREAD

**Issue by YenBenGrey** [PwQt/magic-items-2#89]
**Module Version:** v1.7.1

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
When I open a NPC character sheet (any) and add a feature or item or weapon to that actor, the attached error happens. 
Currently I have no idea what impact this has on my game or world I am just sending feedback. 
I am on all the latest versions of MidiQol, DAE, CPR, Dfreds CE.

**To Reproduce**
1. Go to NPC character sheet in sidebar
2. Click on add in the Features tab
3. That is it, go to console

**Expected behavior**
No error

**Screenshots**

**Browser:**
 Chrome

**Foundry Version:** 
11.315
**Game System:** 
DND5e V3.0.4
<img width="1476" alt="image" src="https://github.com/PwQt/magic-items-2/assets/98095856/f3ae7d88-2605-4542-8ffd-3be9e70a91c9">

**Comment by PwQt** [comment]
That is most likely due to non-transferred magic-items-2 flag.

Will try and fix that for 4.0 release
