### ISSUE TITLE
[BUG] Some spells work, others don't when put into a magic item

### ISSUE THREAD

**Issue by FGiorgi** [PwQt/magic-items-2#93]
**Module Version:** v1.7.2

**Describe the bug**
I put a bunch of spells on a magic item. Most of them work, but some don't, they don't even appear in chat. and I get a console error.

**To Reproduce**
Not sure if it can be easily reproduced. I can't find out why some spells work and some doesn't. If it helps for me the not working spells are Bigby's hands and Telekinesys

**Expected behavior**
All spells should work

**Screenshots**
![image](https://github.com/PwQt/magic-items-2/assets/30195951/efb2627b-3ddc-479b-a06e-8e7f7a5fa9ac)

**Browser:**
Chrome 

**Foundry Version:** 
v11.315

**Game System:** 
D&D5e v3.0.4

**Comment by PwQt** [comment]
Have you done the [1.7.0](https://github.com/PwQt/magic-items-2/releases/tag/1.7.0) command execution? 

Could you please try and use the spell with monks-combat-details ?

**Comment by FGiorgi** [comment]
Tried with Monks Combat Details disabled and ran the macro... still not working

![image](https://github.com/PwQt/magic-items-2/assets/30195951/8de0cc0a-71e0-45af-b405-018b0cafdbae)

**Comment by PwQt** [comment]
I hadn't come upon the issue with the new release: https://github.com/PwQt/magic-items-2/pull/92
