### ISSUE TITLE
Incompatibility between Magic Items and Babele[BUG]

### ISSUE THREAD

**Issue by Melkyor** [PwQt/magic-items-2#99]
**Module Version:** v4

**Describe the bug**
Hi,
I noticed that the Magic Items section did not appear in the Spellbook of the character sheet.
After some investigation, it is in fact an incompatibility between Babele, the translation module, and Magic Items.

I don't know if it's up to you to comment on this, but I wanted to at least point it out to you.

Sincerely

**Browser:**
 - Brave

**Foundry Version:** 
- 11.315

**Game System:** 
- DND5e 3.1

**Comment by TheMorningStarLucifer** [comment]
Same here

**Browser:**

- Chrome

**Foundry Version:**

- 11.315

**Game System:**

- 3.1

![image](https://github.com/PwQt/magic-items-2/assets/137843163/afc3c594-cd45-4724-b0fd-05a1b8c92761)

**Comment by PwQt** [comment]
@Melkyor @TheMorningStarLucifer could you please provide me with an example on how can I setup Babele so that I break Magic Items?

**Comment by Flop35190** [comment]
I can tell you what's happening to me but I don't speak English and I'm bad at computers. When Babele is active, magic items do not appear in the spell tab of some player characters but appear on others. When the Babele module is not activated, everything works normally. If you need further details, I will try to give them to you. If you need further details, I will try to give them to you. I will be really happy if you manage to resolve this bug!
![image 2](https://github.com/PwQt/magic-items-2/assets/74499213/f0237b37-d663-4324-8926-83234da2dda1)
![image 1](https://github.com/PwQt/magic-items-2/assets/74499213/b2d0813b-48ff-483c-a6cc-8fedcfd7a1fe)

**Comment by Flop35190** [comment]
As you see, the same magic item is on both character sheets but only appears in the spell book of one of them.

**Comment by Flop35190** [comment]
Here is the Babele configuration menu: there are not many possible options.
![image](https://github.com/PwQt/magic-items-2/assets/74499213/972df803-216e-4b49-93a1-358697111a14)

**Comment by PwQt** [comment]
@Flop35190 
Pourriez-tu me donner le result de console (f12) quand tu ouvre la feuille de caractere qui n'as pas le Magic Item

_Je n'ai parlais pas francais, il y a quelques ans, donc ce peut-etre un peu bizarre a lire 😅 💦 _

**Comment by Flop35190** [comment]
Thank you for your response in French! I cheat, I use Google translate :)
Voilà ma console : 
![image](https://github.com/PwQt/magic-items-2/assets/74499213/8c578af8-8d45-424f-8e64-55601506cd5e)

**Comment by PwQt** [comment]
Malheureusement, ca ne m'aide pas...

Je vais d'essayer de reproduire cet erreur dans les jours suivantes. Au moins tu as donne les parametres du module 🥳 .

**Comment by PwQt** [comment]
Found the bug - this will be fixed in next release

**Comment by Flop35190** [comment]
Well done ! Thank you very much !

**Comment by Melkyor** [comment]
I just updated the module and now it works very well.
Thank you for your responsiveness ! :)
